### ISSUE TITLE
Possible typo in readme

### ISSUE THREAD

**Issue by unscsprt** [penguinpress/watchmaker.js#2]
> The code is ported from Think Pascal 4.0, using the cleaned up source provided by Alan Canon. Alan has produced high fidely versions made for desktop use and ported the code to a more modern version of Pascal. You can get hold of his code on SourceForge.

Should this read, "produced high fidelity versions"?

**Comment by MathieuLoutre** [comment]
Yes, it should! Fixed now. Thanks!
